#+TITLE: Emacs Configuration
#+AUTHOR: Daniël de Kok

* Introduction

This org-mode document stores my main Emacs configuration. I initially
used [[http://spacemacs.org][Spacemacs]] to get an Emacs that is as similar to vim as
possible. Spacemacs is awesome, but also quite slow and buggy. So I
decided to start from scratch. However, my Spacemacs origins still
show, since I culled some key bindings from Spacemacs.

** Tangling

To load the configuration, I use tangling of Emacs lisp fragments,
which are loaded from [[./init.el][init.el]]. Since loading using ~org-babel-load-file~
is slow, I use the [[http://www.holgerschurig.de/en/emacs-efficiently-untangling-elisp/][untangling approach]] proposed by Holger Schurig.

* Package management

#+BEGIN_SRC emacs-lisp
  (require 'package)
  (setq package-enable-at-startup nil)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  (eval-when-compile
    (require 'use-package))
  (require 'diminish)
  (require 'bind-key)
#+END_SRC

* Appearance
** Cleanup

Emacs has some UI elements that I do not use and waste screen space,
in particular:

- The tool bar
- The scroll bar
- The menu bar (outside macOS)

Disable these UI elements:

#+BEGIN_SRC emacs-lisp
(when window-system
  (dolist (mode
	   '(tool-bar-mode
	     tooltip-mode
	     scroll-bar-mode
	     menu-bar-mode
	     blink-cursor-mode))
    (funcall mode 0)))
#+END_SRC

** Font

Set /Operator Mono/ as the main font. This font has the advantage
of supporting italic text.

#+BEGIN_SRC emacs-lisp
  (when window-system
    (set-default-font "Operator Mono 15"))
#+END_SRC

** Theme

The standard Emacs theme is blinding :).

#+BEGIN_SRC emacs-lisp
  (use-package monokai-theme
    :ensure t
    :config
    (load-theme 'monokai t))
#+END_SRC

* Evil

#+BEGIN_SRC emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-C-i-jump nil)
    (evil-mode 1))

  (use-package which-key
    :ensure t
    :init (which-key-mode)

    :config
    (which-key-setup-side-window-right-bottom)
    (setq which-key-sort-order 'which-key-key-order-alpha
          which-key-side-window-max-width 0.33
          which-key-idle-delay 0.05)
  )
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package general
    :ensure t
    :config
    (general-evil-setup t)

    (general-define-key
     :states '(normal motion emacs)
     :prefix "SPC"
     "b"  '(:ignore t :which-key "Buffer")
     "bb" '(ivy-switch-buffer "Switch buffer")
     "bd" '(kill-this-buffer "Kill buffer")

     "f"  '(:ignore t :which-key "File")
     "fs" '(save-buffer)
     "fr" '(ivy-recentf "Recent file")

     "wv" '(split-window-horizontally :which-key "split vertical")
     "ws" '(split-window-vertically :which-key "split horizontal")
     "wk" '(evil-window-up :which-key "up")
     "wj" '(evil-window-down :which-key "down")
     "wh" '(evil-window-left :which-key "left")
     "wl" '(evil-window-right :which-key "right")
     "wd" '(delete-window :which-key "delete")
     ))
#+END_SRC

* Ivy

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :ensure t
  :diminish (ivy-mode . "")
  :init (ivy-mode 1)
  :config
  (setq ivy-use-virtual-buffers t)
  (setq ivy-hight 20)
  (setq ivy-count-format "(%d/%d) ")
)

(use-package counsel
  :ensure t
  :bind*                           ; load counsel when pressed
  (("M-x"     . counsel-M-x)       ; M-x use counsel
   ("C-x C-f" . counsel-find-file) ; C-x C-f use counsel-find-file
   ("C-x C-r" . counsel-recentf)   ; search recently edited files
   ("C-c f"   . counsel-git)       ; search for files in git repo
   ("C-c s"   . counsel-git-grep)  ; search for regexp in git repo
   ("C-c /"   . counsel-ag)        ; search for regexp in git repo using ag
   ("C-c l"   . counsel-locate))   ; search for files or else using locate
)
#+END_SRC

* Source management

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t
    :general
    (:states '(normal motion emacs)
     :prefix "SPC"
     "g"  '(:ignore t :which-key "Git")
     "gs" 'magit-status)

    :config
    (use-package evil-magit
      :ensure t))
#+END_SRC

* org mode

#+BEGIN_SRC emacs-lisp
  (use-package org
    :ensure t
    :general
    (:states '(normal motion emacs)
     :keymaps 'org-mode-map
     :prefix "SPC"
     "m"  '(:ignore t :which-key "Mode")
     "ma" '(org-agenda :which-key "Agenda")
     "mA" '(org-archive-subtree :which-key "Archive")
     "md" '(org-deadline :which-key "Deadline")
     "me" '(org-export-dispatch :which-key "Export")
     "mP" '(org-set-property :which-key "Property")
     "m:" '(org-set-tags :which-key "Tags")

     ;; tables
     "mtdc" '(org-table-delete-column)
     "mtdr" '(org-table-kill-row)
     "mte" '(org-table-eval-formula)
     "mtE" '(org-table-export)
     "mth" '(org-table-previous-field)
     "mtH" '(org-table-move-column-left)
     "mtic" '(org-table-insert-column)
     "mtih" '(org-table-insert-hline)
     "mtiH" '(org-table-hline-and-move)
     "mtir" '(org-table-insert-row)
     "mtI" '(org-table-import)
     "mtj" '(org-table-next-row)
     "mtJ" '(org-table-move-row-down)
     "mtK" '(org-table-move-row-up)
     "mtl" '(org-table-next-field)
     "mtL" '(org-table-move-column-right)
     "mtn" '(org-table-create)
     "mtN" '(org-table-create-with-table.el)
     "mtr" '(org-table-recalculate)
     "mts" '(org-table-sort-lines)
     "mttf" '(org-table-toggle-formula-debugger)
     "mtto" '(org-table-toggle-coordinate-overlays)
     "mtw" '(org-table-wrap-region))

    (:states '(normal motion emacs)
     :prefix "SPC"

     ;; Global agenda mappings
     "ao#" '(org-agenda-list-stuck-projects)
     "ao/" '(org-occur-in-agenda-files)
     "aoa" '(org-agenda-list)
     "aoe" '(org-store-agenda-views)
     "aom" '(org-tags-view)
     "aoo" '(org-agenda)
     "aos" '(org-search-view)
     "aot" '(org-todo-list)

     ;; other
     "aoO" '(org-clock-out)
     "aoc" '(org-capture)
     "aol" '(org-store-link))

    (general-define-key
     :keymaps 'org-agenda-mode-map
     "h" 'evil-backward-char
     "l" 'evil-forward-char
     "j" 'evil-next-line
     "k" 'evil-previous-line)

    :config
    (add-hook 'org-mode-hook
              (lambda () (add-to-list 'write-file-functions 'delete-trailing-whitespace)))

    (setq org-agenda-files '("~/git/org/")
	  org-latex-create-formula-image-program 'imagemagick
	  org-latex-table-scientific-notation "$%s\\times10^{%s}$")

    (org-babel-do-load-languages
     'org-babel-load-languages
     '((gnuplot . t)
       (python . t)
       (latex . t))))

  (use-package org-ref
    :ensure t
    :init
    ;;:mode "\\.org\\'"
    :after org
    :general
    (:states '(normal motion emacs)
     :prefix "SPC"
     :keymaps 'bibtex-mode-map
     "mh" '(org-ref-bibtex-hydra/body :which-key "BibTeX hydra"))
    :config
    (setq org-ref-default-bibliography '("~/git/papers/references.bib")
	  org-ref-pdf-directory "~/git/papers/"
	  org-ref-bibliography-notes "~/git/org/literature.org"))

  (use-package evil-org
    :ensure t
    :after org
    :config
    (add-hook 'org-mode-hook 'evil-org-mode)
    (add-hook 'evil-org-mode-hook
	      (lambda ()
		(evil-org-set-key-theme '(todo)))))

  (use-package org-bullets
    :ensure t
    :after org
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
    (setq org-bullets-bullet-list '("①" "②" "③ " "④" "⑤" "⑥" "⑦" "⑧" "⑨" "⑩" "⑪" "⑫" "⑬" "⑭" "⑮")))


#+END_SRC
* Programming languages
** Company

Use ~company~ for completion.

#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :init (company-mode))
#+END_SRC
** Flycheck
~flycheck~ provides online syntax checking.

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :init (global-flycheck-mode))
#+END_SRC

** Rust

Load ~rust-mode~ to make editing Rust code more comfortable.

#+BEGIN_SRC emacs-lisp
  (use-package rust-mode
    :ensure t
    :mode "\\.rs\\'")
#+END_SRC

Use ~racer~ for completions.

#+BEGIN_SRC emacs-lisp
  (use-package racer
    :ensure t
    :after rust-mode
    :config
    (add-hook 'rust-mode-hook #'racer-mode)
    (add-hook 'racer-mode-hook #'eldoc-mode)
    (add-hook 'racer-mode-hook #'company-mode)
    (define-key rust-mode-map (kbd "TAB") #'company-indent-or-complete-common)
    (setq company-tooltip-align-annotations t))
#+END_SRC

~flycheck-rust~ provides online syntax checking.

#+BEGIN_SRC emacs-lisp
  (use-package flycheck-rust
    :ensure t
    :after rust-mode
    :config
    (add-hook 'flycheck-mode-hook #'flycheck-rust-setup))
#+END_SRC
* TeX

#+BEGIN_SRC emacs-lisp
  (use-package tex
    :ensure auctex
    :mode ("\\.tex\\'" . TeX-latex-mode)

    :config
    (use-package latex
      :defer t
      :config
      (use-package preview)
      (add-hook 'LaTeX-mode-hook 'reftex-mode)))

#+END_SRC

* Miscelaneous
** Workspaces

#+BEGIN_SRC emacs-lisp
  (use-package eyebrowse
    :ensure t
    :init
    (eyebrowse-mode t)
    :config
    (eyebrowse-setup-opinionated-keys)
  )
#+END_SRC

** Projects

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t
    :general
    (:states '(normal motion emacs)
     :prefix "SPC"
     "p"  '(:ignore t :which-key "Project")
     "pf" '(projectile-find-file :which-key "Find in project")
     "pl" '(projectile-switch-project :which-key "Switch project"))

    :init (projectile-mode 1)

    :config
    (progn
      (setq projectile-enable-caching t)
      (setq projectile-require-project-root nil)
      (setq projectile-completion-system 'ivy)
      (add-to-list 'projectile-globally-ignored-files ".DS_Store")))
#+END_SRC

** Rainbow delimiters

#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :config
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode)
  )
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq reftex-default-bibliography '("~/git/papers/references.bib"))
#+END_SRC
** Relative line numbers

Use relative line numbers to ease evil operations. ~nlinum-relative~
only recomputes line numbers when Emacs is idle, speeding up line
numbering in large files.

#+BEGIN_SRC emacs-lisp
  (use-package nlinum-relative
    :ensure t
    :config
    (nlinum-relative-setup-evil)
    (add-hook 'prog-mode-hook 'nlinum-relative-mode)
    (add-hook 'org-mode-hook 'nlinum-relative-mode))
#+END_SRC
